from io import BytesIO
import zipfile
from typing import Any

def build_fastapi_project_zip(blueprint: Any) -> BytesIO:
    """Create a minimal ZIP BytesIO as a placeholder for the real generator.

    The real implementation was moved; this stub lets the backend run until
    the full generator is restored.
    """
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("README.md", "Placeholder FastAPI project generated by backand_product stub\n")
    buf.seek(0)
    return buf

def generate_init_sql(blueprint: Any) -> str:
    return "-- placeholder init sql"

def generate_sqlalchemy_models(blueprint: Any) -> str:
    return "# placeholder SQLAlchemy models"

def generate_docker_compose(blueprint: Any) -> str:
    return "version: '3'\nservices:\n  app:\n    image: alpine\n"
