from jinja2 import Template
from app.schemas.blueprint import ProjectBlueprint

def generate_docker_compose(blueprint: ProjectBlueprint) -> str:
    template_str = """version: '3.8'

# Auto-Generated by Aepra-Forge Architect
services:
  db:
    image: {{ meta.engine }}:16-alpine
    container_name: aepra_generated_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      # File init.sql akan dieksekusi otomatis di sini
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
"""
    jinja_template = Template(template_str)
    return jinja_template.render(meta=blueprint.meta)