from jinja2 import Template
from app.schemas.blueprint import ProjectBlueprint

def generate_init_sql(blueprint: ProjectBlueprint) -> str:
    """
    Fungsi ini menerima data JSON yang sudah tervalidasi, 
    dan mencetaknya menjadi string SQL siap pakai.
    """
    
    # Ini adalah "cetakan" (template) dasar SQL kita
    template_str = """-- ==========================================
-- Auto-Generated by Aepra-Forge Architect
-- Version: {{ meta.version }} | Engine: {{ meta.engine }}
-- ==========================================

{% for table in tables %}
CREATE TABLE {{ table.name }} (
{%- for col in table.columns %}
    {{ col.name }} {{ col.type }}{% if col.length %}({{ col.length }}){% endif %}{% if col.primary %} PRIMARY KEY{% endif %}{% if col.unique %} UNIQUE{% endif %}{% if not col.nullable %} NOT NULL{% endif %}{% if col.default %} DEFAULT {{ col.default }}{% endif %}{{ "," if not loop.last else "" }}
{%- endfor %}
);

{% endfor %}
"""

    # Masukkan template ke mesin Jinja2
    jinja_template = Template(template_str)
    
    # Cetak hasilnya dengan memasukkan data dari Pydantic
    sql_result = jinja_template.render(
        tables=blueprint.tables,
        meta=blueprint.meta
    )
    
    return sql_result